### ISSUE TITLE
Need a list of ads-events

### ISSUE THREAD

**Issue by sgromkov** [neuron-digital/wjplayer#11]
Hi superguys!
I used your wjplayer with ads. I need to catch the ads pause event, to create a big "Play" button over the top advertising layer.

I am sure that this is a very simple task, but I can't find the correct event to listen. 

Is there a list of ads event? Or if it hasn't, may be you cood help me with some advise, how can I make it without change the core file?

My code is simple:
```
var player = wjplayer({
        containerId: 'spb_player',
        autoplay: true,
        debug: true,
        sources: [{
            src: '<?=$hls_url?>',
            type: 'application/x-mpegURL'
        }],
        ads: {
            debug: true,
            adLabel: 'Реклама',
            contribAdsSettings: {
                prerollTimeout: 500
            },
            adTagUrl: adsPrerollUrl
        }
    });
```

It'll be great if wjplayer has something like this:
```
    ads: {
            debug: true,
            adLabel: 'Реклама',
            contribAdsSettings: {
                prerollTimeout: 500
            },
            adTagUrl: adsPrerollUrl,
            onAdPaused: function() {
                // here I will generate my custom "Play" button and showing it over the Ads.
            },
            onAdPlayed: function() {
                // here I will removed or hidded my custom "Play" button.
            },
        }
```

**Comment by mkhazov** [comment]
Take a look at https://github.com/videojs/videojs-contrib-ads#plugin-events

You will need `adstart` and `adend` events:
```player.on('adstart', callback);```
```player.on('adend', callback);```

**Comment by sgromkov** [comment]
Thanks, **mkhazov**.

It works with `start `and `finish` ads events. And I see they didn't realized the `pause` event.

So I will fork and modify the videojs-ima plugin to create the additional button and catch the event.
