### ISSUE TITLE
Скомпелированные дистурбутивы

### ISSUE THREAD

**Issue by supersh86** [neuron-digital/wjplayer#16]
Привет, наткнулся на ваш плеер. К сожалению как я понял получить готовые дистурбутивы можно только через npm. Можете в релизах уже класть готовые дистры, не все к сожалению могут работать с npm.
Заранее спасибо!

**Comment by avdeev** [comment]
@supersh86 День добрый!
Любой дистрибутив в NPM доступ для скачивания, например, через CDN.

https://unpkg.com/wjplayer@1.7.0/
https://cdn.jsdelivr.net/npm/wjplayer@1.7.0/

Вы можете скачать их оттуда и положить в Ваш проект.

**Comment by supersh86** [comment]
Спасибо, не знал.

**Comment by supersh86** [comment]
Алексей, еще один маленький вопрос. Вы не думали сделать поддержку других vpaid vast плагинов. 
Например этого 
https://github.com/MailOnline/videojs-vast-vpaid/tree/RELEASE
Google ima обычно спокойно блокируются адблоком.

**Comment by avdeev** [comment]
@supersh86 Не думали.
Но если есть желание добавить, то будем рады Вашему Pull Request :)
