### ISSUE TITLE
Move browser deps to dependencies section

### ISSUE THREAD

**Issue by avdeev** [neuron-digital/wjplayer#2]

**Comment by mkhazov** [comment]
I don't want all dependencies to be installed when installing this package on production, because only dist files are needed there.

**Comment by avdeev** [comment]
They will not be installed

You distribute only the dist files

For example, in this package you store video.js and other browser deps in dependencies section

https://github.com/mkhazov/videojs-share/blob/master/package.json#L76

**Comment by mkhazov** [comment]
It's because they must be installed: https://github.com/mkhazov/videojs-share/blob/master/scripts/modules.rollup.config.js#L5

**Comment by mkhazov** [comment]
If I put `videojs-share` to `dependencies` section, the command `npm install wjplayer` will install `wjplayer`, its dependency `videojs-share` and all its dependencies.

**Comment by avdeev** [comment]
Ok, you right

I close this issue
